vscode:
  extensions:
    - "dbaeumer.vscode-eslint"
    - "ms-azuretools.vscode-docker"
    - "esbenp.prettier-vscode"
    - "mhutchie.git-graph"
    - "eamodio.gitlens"
    - "johnsoncodehk.volar"
gitConfig:
  "pull.rebase": "false"
tasks:
  - init: docker-compose --profile dev build
    command: |
      cp .env.example .env
      echo "SITE_URL=$(gp url 3001)" >> .env
      echo "API_URL=$(gp url 8000)" >> .env
      echo "GITPOD_WORKSPACE_URL=$(gp url 3001)" >> .env

      docker-compose --profile dev up -d
      sudo docker-compose cp vue-app-dev:/app/node_modules ./client-ui/
      sudo docker-compose cp server:/app/node_modules ./server/
ports:
  - port: 8000
    visibility: public
